version: '2'
services:
   elasticsearch:
      build: ./elasticsearch/.
      ports:
         - 9200:9200
         - 9300:9300
      volumes:
         - ./data:/usr/share/elasticsearch/data
   kibana:
      build: ./kibana/.
      ports:
         - 5601:5601
